version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metrix
      POSTGRES_PASSWORD: metrix
      POSTGRES_DB: strapi_test
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: strapi_test
      MYSQL_USER: metrix
      MYSQL_PASSWORD: metrix
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: metrix
    volumes:
      - mysqldata_test:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  pgdata_test:
  mysqldata_test:
