version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metrix
      POSTGRES_PASSWORD: metrix
      POSTGRES_DB: metrix
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: metrix
      MYSQL_USER: metrix
      MYSQL_PASSWORD: metrix
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: metrix
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  pgdata:
  mysqldata:
