name: 'Publish Prerelease'

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        description: 'The tag you want to publish to NPM'
        default: 'experimental'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'metrix-labs/metrix'
    steps:
      - uses: actions/checkout@v4

      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish prerelease
        run: ./scripts/pre-publish.sh
        env:
          # Unique but short prerelease version, e.g. 0.0.0-experimental.1234
          VERSION: "0.0.0-${{ github.event.inputs.dist-tag }}.${{ github.run_number }}"
          DIST_TAG: ${{ github.event.inputs.dist-tag }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
