name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'The version bump'
        options: [patch, minor, prepatch, preminor]
      distTag:
        type: choice
        description: 'NPM dist-tag'
        default: latest
        options: [latest, beta, rc, alpha]

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    if: github.repository == 'metrix-labs/metrix'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: ./scripts/publish.sh
        env:
          VERSION: ${{ github.event.inputs.version }}
          DIST_TAG: ${{ github.event.inputs.distTag }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
